/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as BImport } from './routes/b'
import { Route as AImport } from './routes/a'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const BRoute = BImport.update({
  path: '/b',
  getParentRoute: () => rootRoute,
} as any)

const ARoute = AImport.update({
  path: '/a',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/a': {
      preLoaderRoute: typeof AImport
      parentRoute: typeof rootRoute
    }
    '/b': {
      preLoaderRoute: typeof BImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([IndexRoute, ARoute, BRoute])

/* prettier-ignore-end */
